# Site
name: "TOP Squad"
title: "TOP Squad Blog"
description: "Uitlaatklep voor alle Toppers van TOP Squad."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
#google_analytics: 'UA-46278016-1'
#disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  joey.roosing:
    name: Joey Roosing
    display_name: Joey Roosing
    email: joey.roosing@top-squad.nl
    web: https://top-squad.nl
    description: "Developer bij Top Squad"
  benjamin.faal:
    name: Benjamin Faal
    display_name: Benjamin Faal
    email: benjamin.faal@top-squad.nl
    web: https://top-squad.nl
    description: "Developer bij Top Squad"
  marc.huls:
    name: Marc Huls
    display_name: Marc Huls
    email: marc.huls@top-squad.nl
    web: https://top-squad.nl
    description: "Developer bij Top Squad"
  masudul.haque:
    name: Masudul Haque
    display_name: Masudul Haque
    email: masudul.haque@top-squad.nl
    web: https://top-squad.nl
    description: "Developer bij Top Squad"
  sandra.boekhout:
    name: Sandra Boekhout
    display_name: Sandra Boekhout
    email: sandra.boekhout@top-squad.nl
    web: https://top-squad.nl
    description: "Verbinder bij Top Squad"
  theo.janssen:
    name: Theo Janssen
    display_name: Theo Janssen
    email: theo.janssen@top-squad.nl
    web: https://top-squad.nl
    description: "Developer bij Top Squad"  
  sander.dahlberg:
    name: Sander Dahlberg
    display_name: Sander Dahlberg
    gravatar: 15b8430273ba063edbada7ffc1cfc08f
    email: sander.dahlberg@top-squad.nl
    web: https://top-squad.nl
    description: "Developer en oprichter bij Top Squad"
  sander.hautvast:
    name: Sander Hautvast
    display_name: Sander Hautvast
    gravatar: c50cfcd38195af19d0f092b8d7dc15bc
    email: sander.hautvast@top-squad.nl
    web: https://top-squad.nl
    description: "Developer bij Top Squad"
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
